image: bradrydzewski/go:1.4
git:
  path: git.target.com/gophersaurus/gf
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - go version
  - go get -u git.target.com/gophersaurus/gf
  - gf -h
  - cd cd $GOPATH/src
  - mkdir github.com
  - cd github.com
  - mkdir org
  - cd org
  - gf new test
  - go get ./...
  - go build
