image: bradrydzewski/go:1.4
git:
  path: github.com/gophersaurus/gf
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:

  # print golang version
  - go version

  # get the gf tool
  - go get -v github.com/gophersaurus/gf
  - gf -h

  # create directories
  - cd $GOPATH/src/github.com
  - mkdir org
  - cd org

  # create new test project
  - gf new -s -sg test

  # show it worked
  - sudo apt-get install tree
  - tree test
  - cat test/main.go
