image: bradrydzewski/go:1.4
git:
  path: git.target.com/gophersaurus/gf
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:

  # print golang version
  - go version

  # get the gf tool
  - go get -u -v git.target.com/gophersaurus/gf.v1
  - go get -u -v git.target.com/gophersaurus/gf
  - gf -h

  # create directories
  - cd $GOPATH/src/github.com
  - mkdir org
  - cd org

  # create new test project
  - gf new -s -sg test

  # get deps and build
  - go get ./...
  - go build
