image: bradrydzewski/go:1.4
git:
  path: git.target.com/gophersaurus/gf
env:
  - PATH=$PATH:$GOPATH/bin
script:

  # print $GOPATH
  - echo $GOPATH
  - ls -la $GOPATH

  # print golang version
  - go version

  # get the gf tool
  - go get -u git.target.com/gophersaurus/gf.v1
  - go get -u git.target.com/gophersaurus/gf
  - gf -h

  # create directories
  - cd $GOPATH/src/github.com
  - mkdir org
  - cd org

  # create new test project
  - gf new -s -sg test

  # get deps and build
  - go get ./...
  - go build
